# Generated by Django 4.2.6 on 2024-11-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('poster', models.CharField(blank=True, max_length=255, null=True)),
                ('overview', models.TextField()),
                ('release_date', models.DateField()),
                ('runtime', models.PositiveIntegerField(help_text='상영 시간(분 단위)')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('adult', models.BooleanField(default=False)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.PositiveIntegerField()),
                ('original_language', models.CharField(blank=True, max_length=50, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('watch_platforms', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actors', models.ManyToManyField(related_name='movies', to='movies.actor')),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
                ('keywords', models.ManyToManyField(blank=True, related_name='movies', to='movies.keyword')),
            ],
        ),
    ]
